spring:
  thymeleaf:
    enabled: false
  jpa:
    properties:
      jadira:
        usertype:
          autoRegisterUserTypes: true

    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  messages:
    basename: validation

  datasource:
    url: jdbc:postgresql://localhost/schedule
    username: dbadmin
    password: hihanpan
    sql-script-encoding: UTF-8

  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
      static-path-pattern: /static/** # Path pattern used for static resources.
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      exclude: /jsp

